export const RESOURCE_TYPES = {
  AUTHOR: 'Author',
  BOOK: 'Book',
  PODCAST: 'Podcast',
  PODCAST_EPISODE: 'PodcastEpisode',
  PASTOR: 'Pastor',
  SONG_ARTIST: 'SongArtist',
  CHURCH: 'Church',
  SERMON_SERIES: 'SermonSeries',
  SERMON: 'Sermon',
  CHAPTER: 'Chapter',
  SHOW: 'Show',
  SEASON: 'Season',
  EPISODE: 'Episode',
  GROUP: 'Group',
  DEVOTIONAL: 'Devotional',
}
