export const RESOURCE_TYPES = {
  AUTHOR: 'Author',
  BOOK: 'Book',
  PODCAST: 'Podcast',
  PASTOR: 'Pastor',
  SONG_ARTIST: 'SongArtist',
  CHURCH: 'Church',
  MINISTRY: 'Ministry',
  SERMON_SERIES: 'SermonSeries',
  SERMON: 'Sermon',
  CHAPTER: 'Chapter',
  SHOW: 'Show',
  SEASON: 'Season',
  EPISODE: 'Episode',
  ARTICLE: 'Article',
  PUBLICATION: 'Publication',
  GROUP: 'Group',
  ANSWERED_PRAYER: 'AnsweredPrayer',
}
